[project]
name = "google-scholar-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "googletrans>=4.0.2",
    "httpx>=0.28.1",
    "mcp[cli]>=1.7.0",
    "scholarly>=1.7.11",
]
